I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 19, in script
    narrator "Дело было в офисе одной государственной IT-конторы..."
  File "game/script.rpy", line 19, in script
    narrator "Дело было в офисе одной государственной IT-конторы..."
  File "renpy/common/000window.rpy", line 122, in _window_auto_callback
    _window_show(auto=True)
  File "renpy/common/000window.rpy", line 70, in _window_show
    renpy.with_statement(trans)
OSError: Couldn't find file 'fon.mp3'.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "/home/temich719/renpy/renpy-8.2.1-sdk/renpy/bootstrap.py", line 359, in bootstrap
    renpy.main.main()
  File "/home/temich719/renpy/renpy-8.2.1-sdk/renpy/main.py", line 635, in main
    run(restart)
  File "/home/temich719/renpy/renpy-8.2.1-sdk/renpy/main.py", line 145, in run
    renpy.execution.run_context(True)
  File "/home/temich719/renpy/renpy-8.2.1-sdk/renpy/execution.py", line 955, in run_context
    context.run()
  File "game/script.rpy", line 19, in script
    narrator "Дело было в офисе одной государственной IT-конторы..."
  File "lib/python3.9/future/utils/__init__.py", line 444, in raise_
  File "game/script.rpy", line 19, in script
    narrator "Дело было в офисе одной государственной IT-конторы..."
  File "/home/temich719/renpy/renpy-8.2.1-sdk/renpy/ast.py", line 2557, in execute
    Say.execute(self)
  File "/home/temich719/renpy/renpy-8.2.1-sdk/renpy/ast.py", line 583, in execute
    statement_name(stmt_name)
  File "/home/temich719/renpy/renpy-8.2.1-sdk/renpy/ast.py", line 52, in statement_name
    i(name)
  File "renpy/common/000window.rpy", line 122, in _window_auto_callback
    _window_show(auto=True)
  File "renpy/common/000window.rpy", line 70, in _window_show
    renpy.with_statement(trans)
  File "/home/temich719/renpy/renpy-8.2.1-sdk/renpy/exports.py", line 1781, in with_statement
    return renpy.game.interface.do_with(trans, paired, clear=clear)
  File "/home/temich719/renpy/renpy-8.2.1-sdk/renpy/display/core.py", line 1548, in do_with
    return self.interact(trans_pause=True,
  File "/home/temich719/renpy/renpy-8.2.1-sdk/renpy/display/core.py", line 2165, in interact
    repeat, rv = self.interact_core(preloads=preloads, trans_pause=trans_pause, pause=pause, pause_start=pause_start, pause_modal=pause_modal, **kwargs) # type: ignore
  File "/home/temich719/renpy/renpy-8.2.1-sdk/renpy/display/core.py", line 3022, in interact_core
    renpy.audio.audio.periodic()
  File "/home/temich719/renpy/renpy-8.2.1-sdk/renpy/audio/audio.py", line 1205, in periodic
    raise_(exc[0], exc[1], exc[2])
  File "lib/python3.9/future/utils/__init__.py", line 444, in raise_
  File "/home/temich719/renpy/renpy-8.2.1-sdk/renpy/audio/audio.py", line 1183, in periodic_thread_main
    periodic_pass()
  File "/home/temich719/renpy/renpy-8.2.1-sdk/renpy/audio/audio.py", line 1125, in periodic_pass
    c.periodic()
  File "/home/temich719/renpy/renpy-8.2.1-sdk/renpy/audio/audio.py", line 534, in periodic
    topf = load(filename)
  File "/home/temich719/renpy/renpy-8.2.1-sdk/renpy/audio/audio.py", line 72, in load
    rv = renpy.loader.load(fn, directory="audio")
  File "/home/temich719/renpy/renpy-8.2.1-sdk/renpy/loader.py", line 672, in load
    raise IOError("Couldn't find file '%s'." % name)
OSError: Couldn't find file 'fon.mp3'.

Linux-6.7.7-200.fc39.x86_64-x86_64-with-glibc2.38 x86_64
Ren'Py 8.2.1.24030407
Everlasting sucking 1.0
Fri Mar 22 12:36:49 2024
